# -*- coding: utf-8 -*-
"""Deep Learning Fundamentals.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1oa9xDqVv-6giiRznL9cnq58-3ovg55gF

**Coding the Neural Network Components**
"""

import numpy as np
age = 34
experience = 7

topnode_weights = [2, -5]
bottomnode_weights = [1, -2]
output_weights = [3, -1]

# Create NumPy arrays
input_layer = np.array([age, experience])
weights_topnode = np.array(topnode_weights)
weights_bottomnode = np.array(bottomnode_weights)
output_weights = np.array(output_weights)

# Print the values of the variables
print("input_layer:", input_layer)
print("weights_topnode:", weights_topnode)
print("weights_bottomnode:", weights_bottomnode)
print("output_weights:", output_weights)

"""**Coding the Output with Forward Propagation**"""

import numpy as np

# Define input layer and weights
input_layer = np.array([34, 7])
weights_topnode = np.array([2, -5])
weights_bottomnode = np.array([1, -2])
output_weights = np.array([3, -1])

# Calculate the value of the top node
top_node_value = np.sum(input_layer * weights_topnode)

# Calculate the value of the bottom node
bottom_node_value = np.sum(input_layer * weights_bottomnode)

# Print the node values
print("Top Node Value:", top_node_value)
print("Bottom Node Value:", bottom_node_value)

# Create a NumPy array for both node values
hidden_layer_values = np.array([top_node_value, bottom_node_value])

# Calculate the prediction
prediction = np.sum(hidden_layer_values * output_weights)

# Print the prediction value
print("Prediction:", prediction)